apiVersion: batch/v1
kind: CronJob
metadata:
  name: processing
spec:
  schedule: "0 2 * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      backoffLimit: 1
      template:
        spec:
          imagePullSecrets:
          - name: harbor-registry
          tolerations:
          - key: type
            operator: Equal
            value: processing
            effect: PreferNoSchedule
          nodeSelector:
            type: processing
            kubernetes.io/hostname: prowork714209
          volumes:
            - name: input-pvc
              persistentVolumeClaim:
                claimName: input-pvc
            - name: output-pvc
              persistentVolumeClaim:
                claimName: output-pvc
          initContainers:
          - name: download
            image: amazon/aws-cli:2.27.22
            command: ["/bin/sh", "-c"]
            args:
            - |
              aws s3 cp  "s3://backup-common/asinatra/in" /data \
                --endpoint-url https://zoned-ecs.acrist-services.com --recursive
              sleep 10
            env:
            - name: AWS_REQUEST_CHECKSUM_CALCULATION
              value: when_required
            - name: AWS_RESPONSE_CHECKSUM_VALIDATION
              value: when_required
            envFrom:
            - secretRef:
                name: s3-credentials
            volumeMounts:
            - name: input-pvc
              mountPath: /data/in
              subPath: in
          - name: processing
            image: harbor.shared.acrist-services.com/dsy/asinatra-processing:v1.0.0
            command: ["/bin/sh", "-c"]
            args:
            - |
              sleep 500
            volumeMounts:
            - name: input-pvc
              mountPath: /data/in
            - name: output-pvc
              mountPath: /data/out
          containers:
          - name: upload
            image: amazon/aws-cli:2.27.22
            command: ["/bin/sh", "-c"]
            args:
            - |
              sleep 50
              aws s3 cp /data/out/ "s3://backup-common/asinatra/out/" \
                --recursive \
                --endpoint-url https://zoned-ecs.acrist-services.com
              sleep 100
            env:
            - name: AWS_REQUEST_CHECKSUM_CALCULATION
              value: when_required
            - name: AWS_RESPONSE_CHECKSUM_VALIDATION
              value: when_required
            envFrom:
            - secretRef:
                name: s3-credentials
            volumeMounts:
            - name: output-pvc
              mountPath: /data/out
          restartPolicy: OnFailure
